### ISSUE TITLE
Module building video

### ISSUE THREAD

**Issue by fasteddys** [antosubash/Anto.OrchardCore.CMS#2]
Orchard as ASP MVC Core application as well, [_... Orchard Core Framework: An application framework for building modular, multi-tenant applications on ASP.NET Core...._](https://docs.orchardcore.net/en/latest/)

 Hello in your video you mentioned orchard, can you talk about building business features from a module perspective.

Also please consider that ABP commercial is very very expensive for small business to buy, but there are nicer helpers like EASYABPGUI ABP52 etc. So, in the future, please share something that doesn't always lead to a purchase. I don't know if they are sponsoring/paying you, but the audience is much bigger for affordable products

**Comment by antosubash** [comment]
@fasteddys Thanks for the feedback. I know ABP Commercial is expensive. I dont have commercial license that is why I only create videos for Opensource modules. so i'm not sure how i'm making videos that leads to the purchase. I'm still new to this youtube things and still in the learning process. you are looking for module videos in ABP or Orchard Core?

**Comment by fasteddys** [comment]
Yes please orchard (since its free) and also free quick to deploy ASP Core Line of business frameworks/apps or CMS 👍 

You could do a compare video (as an idea)
